### ISSUE TITLE
[Ubuntu 18.04] Installation fails with "tarfile.ReadError: not a gzip file"

### ISSUE THREAD

**Issue by mnksnz** [igraph/python-igraph#206]
I'm trying to install python-igraph with pip and it seems to fail at multiple points. 

```
:~$ pip2 install python-igraph --user
Collecting python-igraph
  Using cached https://files.pythonhosted.org/packages/0f/a0/4e7134f803737aa6eebb4e5250565ace0e2599659e22be7f7eba520ff017/python-igraph-0.7.1.post6.tar.gz
Building wheels for collected packages: python-igraph
  Running setup.py bdist_wheel for python-igraph ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-8r5H8D/python-igraph/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-WYN7Lr --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/igraph
  copying igraph/statistics.py -> build/lib.linux-x86_64-2.7/igraph
  copying igraph/formula.py -> build/lib.linux-x86_64-2.7/igraph
  copying igraph/utils.py -> build/lib.linux-x86_64-2.7/igraph
  copying igraph/cut.py -> build/lib.linux-x86_64-2.7/igraph
  copying igraph/compat.py -> build/lib.linux-x86_64-2.7/igraph
  copying igraph/summary.py -> build/lib.linux-x86_64-2.7/igraph
  copying igraph/layout.py -> build/lib.linux-x86_64-2.7/igraph
  copying igraph/clustering.py -> build/lib.linux-x86_64-2.7/igraph
  copying igraph/datatypes.py -> build/lib.linux-x86_64-2.7/igraph
  copying igraph/configuration.py -> build/lib.linux-x86_64-2.7/igraph
  copying igraph/matching.py -> build/lib.linux-x86_64-2.7/igraph
  copying igraph/__init__.py -> build/lib.linux-x86_64-2.7/igraph
  creating build/lib.linux-x86_64-2.7/igraph/test
  copying igraph/test/atlas.py -> build/lib.linux-x86_64-2.7/igraph/test
  copying igraph/test/layouts.py -> build/lib.linux-x86_64-2.7/igraph/test
  copying igraph/test/operators.py -> build/lib.linux-x86_64-2.7/igraph/test
  copying igraph/test/generators.py -> build/lib.linux-x86_64-2.7/igraph/test
  copying igraph/test/utils.py -> build/lib.linux-x86_64-2.7/igraph/test
  copying igraph/test/structural.py -> build/lib.linux-x86_64-2.7/igraph/test
  copying igraph/test/vertexseq.py -> build/lib.linux-x86_64-2.7/igraph/test
  copying igraph/test/rng.py -> build/lib.linux-x86_64-2.7/igraph/test
  copying igraph/test/homepage.py -> build/lib.linux-x86_64-2.7/igraph/test
  copying igraph/test/edgeseq.py -> build/lib.linux-x86_64-2.7/igraph/test
  copying igraph/test/indexing.py -> build/lib.linux-x86_64-2.7/igraph/test
  copying igraph/test/cliques.py -> build/lib.linux-x86_64-2.7/igraph/test
  copying igraph/test/foreign.py -> build/lib.linux-x86_64-2.7/igraph/test
  copying igraph/test/matching.py -> build/lib.linux-x86_64-2.7/igraph/test
  copying igraph/test/separators.py -> build/lib.linux-x86_64-2.7/igraph/test
  copying igraph/test/games.py -> build/lib.linux-x86_64-2.7/igraph/test
  copying igraph/test/conversion.py -> build/lib.linux-x86_64-2.7/igraph/test
  copying igraph/test/iterators.py -> build/lib.linux-x86_64-2.7/igraph/test
  copying igraph/test/decomposition.py -> build/lib.linux-x86_64-2.7/igraph/test
  copying igraph/test/colortests.py -> build/lib.linux-x86_64-2.7/igraph/test
  copying igraph/test/__init__.py -> build/lib.linux-x86_64-2.7/igraph/test
  copying igraph/test/basic.py -> build/lib.linux-x86_64-2.7/igraph/test
  copying igraph/test/attributes.py -> build/lib.linux-x86_64-2.7/igraph/test
  copying igraph/test/isomorphism.py -> build/lib.linux-x86_64-2.7/igraph/test
  copying igraph/test/bipartite.py -> build/lib.linux-x86_64-2.7/igraph/test
  copying igraph/test/spectral.py -> build/lib.linux-x86_64-2.7/igraph/test
  copying igraph/test/flow.py -> build/lib.linux-x86_64-2.7/igraph/test
  creating build/lib.linux-x86_64-2.7/igraph/app
  copying igraph/app/shell.py -> build/lib.linux-x86_64-2.7/igraph/app
  copying igraph/app/__init__.py -> build/lib.linux-x86_64-2.7/igraph/app
  creating build/lib.linux-x86_64-2.7/igraph/drawing
  copying igraph/drawing/vertex.py -> build/lib.linux-x86_64-2.7/igraph/drawing
  copying igraph/drawing/utils.py -> build/lib.linux-x86_64-2.7/igraph/drawing
  copying igraph/drawing/metamagic.py -> build/lib.linux-x86_64-2.7/igraph/drawing
  copying igraph/drawing/text.py -> build/lib.linux-x86_64-2.7/igraph/drawing
  copying igraph/drawing/coord.py -> build/lib.linux-x86_64-2.7/igraph/drawing
  copying igraph/drawing/shapes.py -> build/lib.linux-x86_64-2.7/igraph/drawing
  copying igraph/drawing/baseclasses.py -> build/lib.linux-x86_64-2.7/igraph/drawing
  copying igraph/drawing/graph.py -> build/lib.linux-x86_64-2.7/igraph/drawing
  copying igraph/drawing/edge.py -> build/lib.linux-x86_64-2.7/igraph/drawing
  copying igraph/drawing/__init__.py -> build/lib.linux-x86_64-2.7/igraph/drawing
  copying igraph/drawing/colors.py -> build/lib.linux-x86_64-2.7/igraph/drawing
  creating build/lib.linux-x86_64-2.7/igraph/remote
  copying igraph/remote/gephi.py -> build/lib.linux-x86_64-2.7/igraph/remote
  copying igraph/remote/nexus.py -> build/lib.linux-x86_64-2.7/igraph/remote
  copying igraph/remote/__init__.py -> build/lib.linux-x86_64-2.7/igraph/remote
  creating build/lib.linux-x86_64-2.7/igraph/vendor
  copying igraph/vendor/texttable.py -> build/lib.linux-x86_64-2.7/igraph/vendor
  copying igraph/vendor/__init__.py -> build/lib.linux-x86_64-2.7/igraph/vendor
  running build_ext
  Cannot find the C core of igraph on this system using pkg-config.
  We will now try to download and compile the C core from scratch.
  Version number of the C core: 0.7.1.post6
  We will also try: 0.7.1
  
  Using temporary directory: /tmp/pip-install-8r5H8D/python-igraph/tmp/igraph.aEP2CN
  Downloading igraph-0.7.1.tar.gz... 100.00%
  Extracting igraph-0.7.1.tar.gz...
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-8r5H8D/python-igraph/setup.py", line 886, in <module>
      setup(**options)
    File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/dist-packages/wheel/bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
      self.run_command(cmd_name)
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-8r5H8D/python-igraph/setup.py", line 570, in run
      detected = buildcfg.download_and_compile_igraph()
    File "/tmp/pip-install-8r5H8D/python-igraph/setup.py", line 647, in download_and_compile_igraph
      if not igraph_builder.run():
    File "/tmp/pip-install-8r5H8D/python-igraph/setup.py", line 502, in run
      return self.download_and_compile()
    File "/tmp/pip-install-8r5H8D/python-igraph/setup.py", line 420, in download_and_compile
      archive = tarfile.open(local_file_full_path, "r:gz")
    File "/usr/lib/python2.7/tarfile.py", line 1693, in open
      return func(name, filemode, fileobj, **kwargs)
    File "/usr/lib/python2.7/tarfile.py", line 1751, in gzopen
      raise ReadError("not a gzip file")
  tarfile.ReadError: not a gzip file
  
  ----------------------------------------
  Failed building wheel for python-igraph
  Running setup.py clean for python-igraph
Failed to build python-igraph
Installing collected packages: python-igraph
  Running setup.py install for python-igraph ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-8r5H8D/python-igraph/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-uEPBu4/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/igraph
    copying igraph/statistics.py -> build/lib.linux-x86_64-2.7/igraph
    copying igraph/formula.py -> build/lib.linux-x86_64-2.7/igraph
    copying igraph/utils.py -> build/lib.linux-x86_64-2.7/igraph
    copying igraph/cut.py -> build/lib.linux-x86_64-2.7/igraph
    copying igraph/compat.py -> build/lib.linux-x86_64-2.7/igraph
    copying igraph/summary.py -> build/lib.linux-x86_64-2.7/igraph
    copying igraph/layout.py -> build/lib.linux-x86_64-2.7/igraph
    copying igraph/clustering.py -> build/lib.linux-x86_64-2.7/igraph
    copying igraph/datatypes.py -> build/lib.linux-x86_64-2.7/igraph
    copying igraph/configuration.py -> build/lib.linux-x86_64-2.7/igraph
    copying igraph/matching.py -> build/lib.linux-x86_64-2.7/igraph
    copying igraph/__init__.py -> build/lib.linux-x86_64-2.7/igraph
    creating build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/atlas.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/layouts.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/operators.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/generators.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/utils.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/structural.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/vertexseq.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/rng.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/homepage.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/edgeseq.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/indexing.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/cliques.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/foreign.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/matching.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/separators.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/games.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/conversion.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/iterators.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/decomposition.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/colortests.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/__init__.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/basic.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/attributes.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/isomorphism.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/bipartite.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/spectral.py -> build/lib.linux-x86_64-2.7/igraph/test
    copying igraph/test/flow.py -> build/lib.linux-x86_64-2.7/igraph/test
    creating build/lib.linux-x86_64-2.7/igraph/app
    copying igraph/app/shell.py -> build/lib.linux-x86_64-2.7/igraph/app
    copying igraph/app/__init__.py -> build/lib.linux-x86_64-2.7/igraph/app
    creating build/lib.linux-x86_64-2.7/igraph/drawing
    copying igraph/drawing/vertex.py -> build/lib.linux-x86_64-2.7/igraph/drawing
    copying igraph/drawing/utils.py -> build/lib.linux-x86_64-2.7/igraph/drawing
    copying igraph/drawing/metamagic.py -> build/lib.linux-x86_64-2.7/igraph/drawing
    copying igraph/drawing/text.py -> build/lib.linux-x86_64-2.7/igraph/drawing
    copying igraph/drawing/coord.py -> build/lib.linux-x86_64-2.7/igraph/drawing
    copying igraph/drawing/shapes.py -> build/lib.linux-x86_64-2.7/igraph/drawing
    copying igraph/drawing/baseclasses.py -> build/lib.linux-x86_64-2.7/igraph/drawing
    copying igraph/drawing/graph.py -> build/lib.linux-x86_64-2.7/igraph/drawing
    copying igraph/drawing/edge.py -> build/lib.linux-x86_64-2.7/igraph/drawing
    copying igraph/drawing/__init__.py -> build/lib.linux-x86_64-2.7/igraph/drawing
    copying igraph/drawing/colors.py -> build/lib.linux-x86_64-2.7/igraph/drawing
    creating build/lib.linux-x86_64-2.7/igraph/remote
    copying igraph/remote/gephi.py -> build/lib.linux-x86_64-2.7/igraph/remote
    copying igraph/remote/nexus.py -> build/lib.linux-x86_64-2.7/igraph/remote
    copying igraph/remote/__init__.py -> build/lib.linux-x86_64-2.7/igraph/remote
    creating build/lib.linux-x86_64-2.7/igraph/vendor
    copying igraph/vendor/texttable.py -> build/lib.linux-x86_64-2.7/igraph/vendor
    copying igraph/vendor/__init__.py -> build/lib.linux-x86_64-2.7/igraph/vendor
    running build_ext
    Cannot find the C core of igraph on this system using pkg-config.
    We will now try to download and compile the C core from scratch.
    Version number of the C core: 0.7.1.post6
    We will also try: 0.7.1
    
    Using temporary directory: /tmp/pip-install-8r5H8D/python-igraph/tmp/igraph.jFCony
    Downloading igraph-0.7.1.tar.gz... 100.00%
    Extracting igraph-0.7.1.tar.gz...
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-8r5H8D/python-igraph/setup.py", line 886, in <module>
        setup(**options)
      File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-8r5H8D/python-igraph/setup.py", line 570, in run
        detected = buildcfg.download_and_compile_igraph()
      File "/tmp/pip-install-8r5H8D/python-igraph/setup.py", line 647, in download_and_compile_igraph
        if not igraph_builder.run():
      File "/tmp/pip-install-8r5H8D/python-igraph/setup.py", line 502, in run
        return self.download_and_compile()
      File "/tmp/pip-install-8r5H8D/python-igraph/setup.py", line 420, in download_and_compile
        archive = tarfile.open(local_file_full_path, "r:gz")
      File "/usr/lib/python2.7/tarfile.py", line 1693, in open
        return func(name, filemode, fileobj, **kwargs)
      File "/usr/lib/python2.7/tarfile.py", line 1751, in gzopen
        raise ReadError("not a gzip file")
    tarfile.ReadError: not a gzip file
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-8r5H8D/python-igraph/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-uEPBu4/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-install-8r5H8D/python-igraph/

```
Thanks!

**Comment by ntamas** [comment]
Something probably went wrong while the setup script tried to download the C core of the igraph library.

The download targets [this URL](http://igraph.org/nightly/get/c/igraph-0.7.1.tar.gz). Please try downloading it manually and check whether it gives you a proper .tar.gz file. (It worked fine for me).

**Comment by ntamas** [comment]
Just download the file anywhere and try to extract it with `tar -xvvzf igraph-0.7.1.tar.gz`. If it works, it should extract a folder named `igraph-0.7.1` with lots of C code inside. This is the igraph library itself. `python-igraph` is just a higher-level interface that connects it to Python, so, during the setup phase of `python-igraph`, it needs to download `igraph-0.7.1.tar.gz`, extract it and link it to its own code. Judging from your initial bug report, the download phase has somehow failed, that's why I'm asking you to try and extract `igraph-0.7.1.tar.gz` manually. If it works, you can remove the `igraph-0.7.1` folder that it has created and simply try again and run `pip3 install python-igraph`. If it doesn't work, we need to figure out why the download fails.

**Comment by mnksnz** [comment]
Thanks. I just tried something else a few seconds before I read this and I managed to install and import it. I just downloaded the [latest release](https://github.com/igraph/python-igraph/releases/download/0.7.1.post6/python-igraph-0.7.1.post6.tar.gz) and typed ```pip2 install python-igraph-0.7.1.post6.tar.gz --user```. Installation was successful but import error was still there.
```  
 In [1]: import igraph
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-73ffca960e68> in <module>()
----> 1 import igraph

/home/naazare/.local/lib/python2.7/site-packages/igraph/__init__.py in <module>()
     32 # pylint: disable-msg=W0401
     33 # W0401: wildcard import
---> 34 from igraph._igraph import *
     35 from igraph._igraph import __version__, __build_date__
     36 from igraph.clustering import *

ImportError: libigraph.so.0: cannot open shared object file: No such file or directory
```


Then, thanks to [this post](https://askubuntu.com/questions/587486/problem-linking-igraph-importerror-libigraph-so-0) I just ran ``` sudo ldconfig ``` and everything worked.

**Comment by RdNetwork** [comment]
I have the same problem using Python 2.7 and Ubuntu 18.04 as well. I have no problem downloading the C core manually, but Pip apparently can't and setup just fails.

The little script above from tueda gives the following:

```
Python 2.7.15+ (default, Nov 27 2018, 23:36:35)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> from urllib import urlretrieve
>>> urlretrieve('http://igraph.org/nightly/get/c/igraph-0.7.1.tar.gz', 'igraph-0.7.1.tar.gz')
('igraph-0.7.1.tar.gz', <httplib.HTTPMessage instance at 0x7f3597f097a0>)
>>> os.system('file igraph-0.7.1.tar.gz')
igraph-0.7.1.tar.gz: HTML document, ASCII text, with very long lines
```
How to solve this?

**Comment by tueda** [comment]
If the problem is the proxy configuration (you may see some error messages in the HTML file you downloaded?), as an user, options would be (1) to use Python3 or (2) to install `igraph` as a library on your system. As far as I understand, `setup.py` of `python-igraph` first tries to search for `igraph` in the system via `pkg-config`. If not detected, then downloads and compiles it.

If you want to fix `setup.py`: I guess `urllib2.urlopen()` should be used in Python2 instead of `urllib.urlretrieve()`.

**Comment by ntamas** [comment]
replaced `urlretrieve()` with `urlopen()` in the setup script; should be okay from the next release onwards. Thanks!
