### ISSUE TITLE
/usr/bin/igraph exception in cls.progressbar.update

### ISSUE THREAD

**Issue by keszybz** [igraph/python-igraph#44]
```
$ /usr/bin/igraph
No configuration file, using defaults
igraph 0.7.1 running inside  Python 3.4.2 (default, Jul  9 2015, 17:24:30) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> g = Graph.Full(300)
>>> g.write_svg('/tmp/save2.svg')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/lib64/python3.4/site-packages/igraph/__init__.py", line 1938, in write_svg
    layout = self.layout(layout, *args, **kwds)
  File "/usr/lib64/python3.4/site-packages/igraph/__init__.py", line 1422, in layout
    l = method(self, *args, **kwds)
  File "/usr/lib64/python3.4/site-packages/igraph/__init__.py", line 1492, in layout_auto
    return self.layout(algo, *args, **kwds)
  File "/usr/lib64/python3.4/site-packages/igraph/__init__.py", line 1422, in layout
    l = method(self, *args, **kwds)
  File "/usr/lib64/python3.4/site-packages/igraph/__init__.py", line 3949, in result
    layout = func(*args, **kwds)
  File "/usr/lib64/python3.4/site-packages/igraph/app/shell.py", line 382, in _progress_handler
    cls.progress_bar.update(percentage, message)
AttributeError: type object 'ClassicPythonShell' has no attribute 'progress_bar'
```

This is in Fedora's mock (buildroot). When running under python2, the same sequence works fine.

**Comment by ntamas** [comment]
Could not reproduce it yet using Python 3.4.0 on Mac OS X, so it's probably OS-specific. Any help with this would be appreciated as I don't have access to Fedora machines. (A detailed list of instructions would also be of some help if I could blindly run it in a Fedora VM).

**Comment by keszybz** [comment]
It seems to be a bytes/text issue:
```
$ python3 /usr/bin/igraph
No configuration file, using defaults
/usr/lib/python3.4/site-packages/IPython/frontend.py:30: UserWarning: The top-level `frontend` package has been deprecated. All its subpackages have been moved to the top `IPython` level.
  warn("The top-level `frontend` package has been deprecated. "
igraph 0.7.1 running inside  Python 3.4.1 (default, Nov  3 2014, 14:38:10) 
Type "copyright", "credits" or "license" for more information.

IPython 3.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
In [1]: app.shell.TerminalController()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-95193e07245c> in <module>()
----> 1 app.shell.TerminalController()

/usr/lib64/python3.4/site-packages/igraph/app/shell.py in __init__(self, term_stream)
    143         for capability in self._STRING_CAPABILITIES:
    144             (attrib, cap_name) = capability.split('=')
--> 145             setattr(self, attrib, self._tigetstr(cap_name) or '')
    146 
    147         # Colors

/usr/lib64/python3.4/site-packages/igraph/app/shell.py in _tigetstr(cap_name)
    172         import curses
    173         cap = curses.tigetstr(cap_name) or ''
--> 174         return re.sub(r'\$<\d+>[/*]?', '', cap)
    175 
    176     def render(self, template):

/usr/lib64/python3.4/re.py in sub(pattern, repl, string, count, flags)
    173     a callable, it's passed the match object and must return
    174     a replacement string to be used."""
--> 175     return _compile(pattern, flags).sub(repl, string, count)
    176 
    177 def subn(pattern, repl, string, count=0, flags=0):

TypeError: can't use a string pattern on a bytes-like object
In [2]: import pdb;pdb.pm()
> /usr/lib64/python3.4/re.py(175)sub()
-> return _compile(pattern, flags).sub(repl, string, count)
(Pdb) up
> /usr/lib64/python3.4/site-packages/igraph/app/shell.py(174)_tigetstr()
-> return re.sub(r'\$<\d+>[/*]?', '', cap)
(Pdb) p cap
b'\r'
```

then the error that I first reported happens because the code in ConsoleProgressBarMixin wraps TerminalController() in a try..except TryError.

**Comment by ntamas** [comment]
Nice catch - although it's still a mystery why I cannot reproduce it on OS X. Replacing lines 173 and 174 with the following would probably solve the issue on Python 3.x while staying backwards compatible with 2.x:

```
        cap = curses.tigetstr(cap_name) or b''
        return re.sub(rb'\$<\d+>[/*]?', '', cap)
```

**Comment by keszybz** [comment]
I tried that already, and it doesn't work, because `cap` is bytes and it fails later on when the capability string is used in a text context.

I wonder if this optimization is necessary at all: on my machine only a few terminfo files match this pattern (vt100, vt102, vt200, teraterm, wsvt25). Those are mostly used in special circumstances (emulated hardware or such) and it seems unlikely that anyone would be running igraph there.

**Comment by ntamas** [comment]
Actually, the entire `TerminalController` class was borrowed from here:

http://code.activestate.com/recipes/475116-using-terminfo-for-portable-color-output-cursor-co/

In the meanwhile, I managed to reproduce the bug so I'll try to come up with a proper workaround soon.

**Comment by ntamas** [comment]
It took a bit more hacking than anticipated, but I think it's okay now; see this patch:

https://github.com/igraph/python-igraph/commit/a1043169bb51746f7e20c8ca8b23b0fd0b537312
