### ISSUE TITLE
Reading graphmlz fails

### ISSUE THREAD

**Issue by RiskyMaor** [igraph/python-igraph#454]
**Describe the bug**
Reading graphmlz file results with a TypeError.
Does not reproduce using `igraph==0.9.0` or using the write_graphml  / Read_GraphML methods.

**To reproduce**
```
import os
import sys
import igraph

# OS
print(os.system("sw_vers"))

# Python and C compiler versions
print(sys.version)

# igraph version
print(igraph.__version__)

# Create graph
full_graph = igraph.Graph.Full(n=10)

# Write as graphmlz
graph_filename = "full_graph.graphmlz"
print(os.path.isfile(graph_filename))
full_graph.write_graphmlz(f=graph_filename)
print(os.path.isfile(graph_filename))

# Reading the graph fails
graph_from_file = igraph.Graph.Read_GraphMLz(f=graph_filename)
```

Output:

```
ProductName:	macOS
ProductVersion:	11.6
BuildVersion:	20G165

3.6.6 (default, Sep  1 2020, 17:06:05) 
[GCC Apple LLVM 12.0.0 (clang-1200.0.26.2)]

0.9.8

False
True

Traceback (most recent call last):
  File "/Users/.pyenv/versions/3.6.6/envs/pynat/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-240cffa2b5a7>", line 24, in <module>
    graph_from_file = igraph.Graph.Read_GraphMLz(f=graph_filename)
  File "/Users/.pyenv/versions/3.6.6/envs/pynat/lib/python3.6/site-packages/igraph/__init__.py", line 2315, in Read_GraphMLz
    return cls.Read_GraphML(tmpfile, directed=directed, index=index)
TypeError: function takes at most 2 arguments (3 given)
```

**Version information**
pip install igraph
0.9.8

**Comment by ntamas** [comment]
Thanks for the report! `Read_GraphMLz` mistakenly tried to forward an argument named `directed=...` to the underlying `Read_GraphML` function; this is now fixed by removing the `directed=...` argument. If you need a quick fix right now, you need to modify `igraph/__init__.py`, line 2315, and remove the `directed=directed, ` part from it.

The fix will be included in igraph 0.9.9 or 0.10.0, whichever comes first.
