### ISSUE TITLE
release-0.7 branch broke compat.py

### ISSUE THREAD

**Issue by abe-winter** [igraph/python-igraph#87]
On CPython version `Python 2.7.11+`.

Traceback:
```
$ python -c "import igraph"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/.../env/local/lib/python2.7/site-packages/igraph/__init__.py", line 36, in <module>
    from igraph.clustering import *
  File "/home/.../env/local/lib/python2.7/site-packages/igraph/clustering.py", line 33, in <module>
    from igraph.compat import property
  File "/home/.../env/local/lib/python2.7/site-packages/igraph/compat.py", line 59, in <module>
    property = __builtins__.property
AttributeError: 'dict' object has no attribute 'property'
```

The problem is here:
https://github.com/igraph/python-igraph/commit/596f1dfcc7040dc49aec6468de8249f5d61ecfbf#diff-432fe2bfb27d3779ba599c6a9295f78fR58

The 0.7.1-post6 tag tests `isinstance(__builtins__, dict)`. release-0.7 branch assumes `__builtins__.property` will work -- it won't.

The confusion here may be because `__builtins__` has dot properties in the python REPL or in a `__main__` module, but is a dictionary elsewhere.

**Comment by ntamas** [comment]
Thanks!
